import './globals.css'
import Header from '../components/header/head'
import Footer from '../components/footer/foot'
import Dnav from '../components/downnav/downnav'
import { Poppins } from 'next/font/google'

const poppins = Poppins({subsets:['latin'],weight:['400'],variable:'--font-poppins'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins bg-slate-100` }>
        <Header/>
        {children}
        <Dnav/>
        <Footer/>
        
      
      </body>
    </html>
  )
}
